### ISSUE TITLE
fixes for electron

### ISSUE THREAD

**Issue by fu-n** [NANJ-COIN/nanjs#2]
i found some problems about nanjs running on electron.

please check below:

1. "No such file or directory" exception in nanjs.wallet.createWallet()

    in wallet.js line 75, i changed kdf "scrypt" to "pbkdf2".
    lib/script.js of keythereum uses "/tmp" and "/dev" directory,
   so we cannot run nanjs on windows.
   perhaps we need to ability to change kdf by config file.
   (or change keythereum?)

2. "Could not spawn process" exception in nanjs transaction

    sync version of XMLHttpRequest through solidity causes
    "Could not spawn process" exception in electron.
    this code expects node but now electron.
    so we need to use async version of XMLHttpRequest
    by passing second argument of SolidityFunction.call()/balanceOf().

my temporary fix is here:
https://github.com/fu-n/nanj-js/commit/15c5791637f7b1550d82e65b7603930f24b069e2

and my debugging application is here:
https://github.com/fu-n/electron_nanjs

how to reproduce issues:
(1) git clone https://github.com/fu-n/electron_nanjs, and cd to cloned directory.
(2) change "fu-n/nanj-js#master" to "NANJ-COIN/nan-js#master" in package.json
(3) do windows build instrunction written in README.
(4) after run app, call createWallet to reproduce issues.

**Comment by giangmd** [comment]
i'm sorry for issue, but currently i can't reproduce this issue in windows. please help me snapshot images.

**Comment by fu-n** [comment]
no problem, nanjs v1.0.1 solved issues.
thanks for your work!

image for 1: press "pause on exception" then createWallet().
![1](https://user-images.githubusercontent.com/41744760/44472055-55238180-a668-11e8-8eea-a8c5e05e2857.png)

image for 2: sorry, "Could not find Electron app" not "Could not spawn process".
![2](https://user-images.githubusercontent.com/41744760/44472056-55238180-a668-11e8-9ce3-8c937713d5a8.png)
